### ISSUE TITLE
Keyboard blocks radio buttons

### ISSUE THREAD

**Issue by pH14** [kwhite17/Nudge#1]
When typing in a Nudge message, the keyboard will appear and block the radio buttons. There's no obvious way to dismiss it without using a back button.

**Comment by kwhite17** [comment]
I implemented a ScrollView so that the radio buttons aren't covered by the keyboard:  [New MessageForm Class](https://github.com/kwhite17/Nudge/commit/a4fdf32190031ebce39fff7b3b6498651d281553#diff-06b30b1983dba52c14f4fbaee14589e9)
